### ISSUE TITLE
scripts/android-pinning: fails with NBC

### ISSUE THREAD

**Issue by 3052** [hyugogirubato/Frida-CodeShare#1]
com.nbcuni.nbc

**Comment by hyugogirubato** [comment]
@3052 I will look over the next few days to see where the problem comes from (if it's java or native).

**Comment by jajabu33** [comment]
@hyugogirubato do you accept paid requests? can i have your email or discord?

**Comment by hyugogirubato** [comment]
I didn’t have time to deal with it last because I was busy with other events. I will look at it in the hours that follow.

**Comment by hyugogirubato** [comment]
> @hyugogirubato do you accept paid requests? can i have your email or discord?

regarding specific work I don't know if I will have time mwis you can always contact me via discord, my pseudonym is the same

**Comment by hyugogirubato** [comment]
@3052 
Bypass pinning works on my side. Make sure you are using Frida Server as root on your device.

![image](https://github.com/hyugogirubato/Frida-CodeShare/assets/65763543/21dae86b-7147-4822-984e-c1971fa4dad7)

**Comment by 3052** [comment]
I need it to work with MITM proxy if possible

**Comment by hyugogirubato** [comment]
> I need it to work with MITM proxy if possible 

I'll test with mitmproxy in 2 hours and I'll tell you

**Comment by hyugogirubato** [comment]
@3052 
I just looked, the problem is linked to your use of mimtproxy and not the script (the script can't do everything). Try to resolve the problem on your side because I can't do anything more for you.
![trusted](https://github.com/hyugogirubato/Frida-CodeShare/assets/65763543/c333d748-f1be-4d7b-bd78-df3670115365)


I attach to this message the certificate specific to mitmproxy android format according to the procedure: [JustTrustMe](https://github.com/81U380X/JustTrustMe/tree/main)

[c8750f0d.0.txt](https://github.com/hyugogirubato/Frida-CodeShare/files/13467608/c8750f0d.0.txt)
[mitmproxy-ca-cert.pem.txt](https://github.com/hyugogirubato/Frida-CodeShare/files/13467609/mitmproxy-ca-cert.pem.txt)

**Comment by 3052** [comment]
yeah I did all that process already. I have used MITM Proxy and Frida for other projects, but not working for NBC. is it working for you with MITM Proxy and NBC?
